### ISSUE TITLE
Používať množné alebo jednotné číslo vo filtri?

### ISSUE THREAD

**Issue by krtko1** [kockatykalendar/frontend#104]
![2021-02-05-125536_grim](https://user-images.githubusercontent.com/21214184/107030987-ca8c5980-67b1-11eb-98e3-e6baa39ce2fa.png)

Ja nemám preferenciu ale som za to aby to bolo jednotné (akože všade rovnaké, nie nutné jednotné :sweat_smile:). Aktuálne vyhráva množné číslo.

**Comment by Zajozor** [comment]
Podla mna to vzniklo takto preto, lebo sutaze su bezne pre viac rocnikov, z viac vied, ale vacsinou maju len jedneho organizatora.

Som za mnozne :)
