### ISSUE TITLE
Toggle na zobrazovanie uplynulých akcii

### ISSUE THREAD

**Issue by krtko1** [kockatykalendar/frontend#49]
Čo keby sme mali možnosť nezobrazovať veci čo už boli? Akože ten autoscroll a všetko je cool ale predsa len to renderovanie nejaký ten čas trvá a vieme potom zobraziť content rýchlejšie. Prípadne zobrazovať defaultne iba mesiac do histórie alebo také dačo.

**Comment by ano95** [comment]
Neviem, či tam je tých akcií toľko, aby sa nám oplatilo riešiť, že sa ich tam veľa renderuje "zbytočne".

**Comment by krtko1** [comment]
#97 rieši aj tento problém, takže to asi nemá zmysel.
