### ISSUE TITLE
Tailwind building

### ISSUE THREAD

**Issue by ano95** [kockatykalendar/frontend#5]
https://tailwindcss.com/docs/installation

Možno by nám stačil ten tailwindcss-cli?

**Comment by N4M3L355** [comment]
jo, na to som úplne zabudol že to ide a pritom to používam :D to by bolo fajn

**Comment by N4M3L355** [comment]
Otázka je že či tailwind.config.js chceme mať v main dir alebo niekde v podpriečinku/inom repe

**Comment by krtko1** [comment]
podľa mňa sme sa dohodli, že to bude v priečinku tailwind
