### ISSUE TITLE
Rozbité logo Riešok

### ISSUE THREAD

**Issue by miroooooooooo** [kockatykalendar/frontend#57]
### Logo na stránke:
![image](https://user-images.githubusercontent.com/35628183/100779866-49a78f00-3409-11eb-8bd6-4113dbae3f83.png)

### Originál:
![image](https://user-images.githubusercontent.com/35628183/100781133-ef0f3280-340a-11eb-89f6-6707c8fe1258.png)

Keďže logo je stale WIP, tak s tým stačí počkať, ale bolo by dobré, kebyže sa pozerá na kvalitu a až potom na veľkosť...

**Comment by ano95** [comment]
Nikto nečakal, že sa bude zobrazovať väčšie 😂 a nakoniec nás to dobehlo. Zajtra vymením späť.
