### ISSUE TITLE
Organizátor "Ostatné"

### ISSUE THREAD

**Issue by miroooooooooo** [kockatykalendar/frontend#58]
Pri filtrovaní organizátorov by bolo dobré mať položku "Ostatné", nech sa dajú pozreť termíny iba jedného organizátora (napr. Riešok)

![kockatykalendar sk_terminy html](https://user-images.githubusercontent.com/35628183/100782479-c8ea9200-340c-11eb-8a5e-857f10546193.png)

**Comment by Zajozor** [comment]
@Na01100101a na toto by si sa mozno tiez vedela pozriet, ci :) ?

(Vsimni si ze v mirovom screenshote su nalavo zvolene len riesky ale v zozname akcii je vidno aj zenity od SIOV - tj. keby si mala vo filtri ostatne, tak vies tie dat prec a vidiet len riesky)

Filter na ostatne je uz spraveny v casti "Vedy" tak mozes spravit nejako to iste.
