### ISSUE TITLE
Tlačidlo v pravo hore v navbare

### ISSUE THREAD

**Issue by krtko1** [kockatykalendar/frontend#70]
![ezgif-3-768246f2f0b2](https://user-images.githubusercontent.com/21214184/100882611-ac536600-34af-11eb-9c26-55f3e2b13fcd.gif)
Trochu to skáče hore dole, lebo scroll bar. Neviem, či to vôbec chceme fixnúť, čo myslíte?

**Comment by Zajozor** [comment]
asi low priority, ale mohol by byt na oboch scrollbar az pod navbarom, co si myslis ty?

**Comment by ano95** [comment]
ja si myslim, ze by to bolo sice pekne, ale neviem, či to stojí za to
