### ISSUE TITLE
Filter bug, znovu

### ISSUE THREAD

**Issue by ano95** [kockatykalendar/frontend#72]
Eventy, ktoré majú len minimálnu požiadavku na účastníkov sa nedajú odfiltrovať preč. (vypnite si obe typy škôl)

![image](https://user-images.githubusercontent.com/11409143/100920804-ed616f80-34db-11eb-8bae-582376099551.png)

**Comment by Zajozor** [comment]
😅

**Comment by ano95** [comment]
Malo by byť fixnuté v #93
