### ISSUE TITLE
Logo nucem a fykos

### ISSUE THREAD

**Issue by krtko1** [kockatykalendar/frontend#74]
máme ich akcie a aktuálne sa nezobrazujú ideálne

**Comment by krtko1** [comment]
Nejaký nápad čo s týmto? https://www.nucem.sk/static/img/nucem--sk.svg zobrať iba to M?

**Comment by ano95** [comment]
Možno by som pri nich len nechal názov "NÚCEM" a logo tam nepchal

**Comment by krtko1** [comment]
Tak aj ako favicon majú to M a robiť iba zobrazovanie textu je v skutočnosti náročnejšie, podľa mňa (nie že by to bol problém) Ale spravím obrázok

**Comment by ano95** [comment]
tak, zobrazenie textu vyriešiš tak, že nezadefinuješ logo, len názov :D
